#pragma once

#define FUZE_MOUSE_BUTTON_1 0
#define FUZE_MOUSE_BUTTON_2 1
#define FUZE_MOUSE_BUTTON_3 2
#define FUZE_MOUSE_BUTTON_4 3
#define FUZE_MOUSE_BUTTON_5 4
#define FUZE_MOUSE_BUTTON_6 5
#define FUZE_MOUSE_BUTTON_7 6
#define FUZE_MOUSE_BUTTON_8 7
#define FUZE_MOUSE_BUTTON_LAST FUZE_MOUSE_BUTTON_8
#define FUZE_MOUSE_BUTTON_LEFT FUZE_MOUSE_BUTTON_1
#define FUZE_MOUSE_BUTTON_RIGHT FUZE_MOUSE_BUTTON_2
#define FUZE_MOUSE_BUTTON_MIDDLE FUZE_MOUSE_BUTTON_3
